name: Deploy
on:
  push:
    branches: [master]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: taiyaki256/discord-kintai

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            docker stop discord-kintai || true
            docker rm discord-kintai || true
            mkdir -p ~/discord-kintai-data
            sudo chown -R 1001:1001 ~/discord-kintai-data
            docker run -d --name discord-kintai --restart unless-stopped \
              -v ~/discord-kintai-data:/home/appuser \
              -e DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}" \
              -e DATABASE_URL="sqlite:/home/appuser/attendance.db" \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
